version: "3.4"
services:
  lb:
    build: ./lb
    ports:
      - "8000:80"
  web1:
    build: ./service1
    ports:
      - "8001:5000"
  web2:
    build: ./service2
    ports:
      - "8002:5000"      
  redis:
    image: "redis:alpine"
